export default [
	{ value: 'admin-appearance', label: 'Admin Appearance' },
	{ value: 'admin-collapse', label: 'Admin Collapse' },
	{ value: 'admin-comments', label: 'Admin Comments' },
	{ value: 'admin-generic', label: 'Admin Generic' },
	{ value: 'admin-home', label: 'Admin Home' },
	{ value: 'admin-links', label: 'Admin Links' },
	{ value: 'admin-media', label: 'Admin Media' },
	{ value: 'admin-network', label: 'Admin Network' },
	{ value: 'admin-page', label: 'Admin Page' },
	{ value: 'admin-plugins', label: 'Admin Plugins' },
	{ value: 'admin-post', label: 'Admin Post' },
	{ value: 'admin-settings', label: 'Admin Settings' },
	{ value: 'admin-site', label: 'Admin Site' },
	{ value: 'admin-tools', label: 'Admin Tools' },
	{ value: 'admin-users', label: 'Admin Users' },
	{ value: 'align-center', label: 'Align Center' },
	{ value: 'align-left', label: 'Align Left' },
	{ value: 'align-none', label: 'Align None' },
	{ value: 'align-right', label: 'Align Right' },
	{ value: 'analytics', label: 'Analytics' },
	{ value: 'archive', label: 'Archive' },
	{ value: 'arrow-down', label: 'Arrow Down' },
	{ value: 'arrow-down-alt', label: 'Arrow Down Alt' },
	{ value: 'arrow-down-alt2', label: 'Arrow Down Alt 2' },
	{ value: 'arrow-left', label: 'Arrow Left' },
	{ value: 'arrow-left-alt', label: 'Arrow Left Alt' },
	{ value: 'arrow-left-alt2', label: 'Arrow Left Alt 2' },
	{ value: 'arrow-right', label: 'Arrow Right' },
	{ value: 'arrow-right-alt', label: 'Arrow Right Alt' },
	{ value: 'arrow-right-alt2', label: 'Arrow Right Alt 2' },
	{ value: 'arrow-up', label: 'Arrow Up' },
	{ value: 'arrow-up-alt', label: 'Arrow Up Alt' },
	{ value: 'arrow-up-alt2', label: 'Arrow Up Alt 2' },
	{ value: 'art', label: 'Art' },
	{ value: 'awards', label: 'Awards' },
	{ value: 'backup', label: 'Backup' },
	{ value: 'book', label: 'Book' },
	{ value: 'book-alt', label: 'Book Alt' },
	{ value: 'businessman', label: 'Businessman' },
	{ value: 'calendar', label: 'Calendar' },
	{ value: 'cart', label: 'Cart' },
	{ value: 'category', label: 'Category' },
	{ value: 'clipboard', label: 'Clipboard' },
	{ value: 'clock', label: 'Clock' },
	{ value: 'cloud', label: 'Cloud' },
	{ value: 'camera', label: 'Camera' },
	{ value: 'chart-area', label: 'Chart Area' },
	{ value: 'chart-bar', label: 'Chart Bar' },
	{ value: 'chart-line', label: 'Chart Line' },
	{ value: 'chart-pie', label: 'Chart Pie' },
	{ value: 'dashboard', label: 'Dashboard' },
	{ value: 'desktop', label: 'Desktop' },
	{ value: 'dismiss', label: 'Dismiss' },
	{ value: 'download', label: 'Download' },
	{ value: 'edit', label: 'Edit' },
	{ value: 'editor-aligncenter', label: 'Editor Align Center' },
	{ value: 'editor-alignleft', label: 'Editor Align Left' },
	{ value: 'editor-alignright', label: 'Editor Align Right' },
	{ value: 'editor-bold', label: 'Editor Blod' },
	{ value: 'editor-break', label: 'Editor Break' },
	{ value: 'editor-contract', label: 'Editor Contract' },
	{ value: 'editor-code', label: 'Editor Code' },
	{ value: 'editor-customchar', label: 'Editor Custom Character' },
	{ value: 'editor-distractionfree', label: 'Editor Distraction-Free' },
	{ value: 'editor-expand', label: 'Editor Expand' },
	{ value: 'editor-help', label: 'Editor Help' },
	{ value: 'editor-indent', label: 'Editor Indent' },
	{ value: 'editor-insertmore', label: 'Editor Insert More' },
	{ value: 'editor-italic', label: 'Editor Italic' },
	{ value: 'editor-justify', label: 'Editor Justify' },
	{ value: 'editor-kitchensink', label: 'Editor Kitchen Sink' },
	{ value: 'editor-ol', label: 'Editor OL' },
	{ value: 'editor-outdent', label: 'Editor Outdent' },
	{ value: 'editor-paragraph', label: 'Editor Paragraph' },
	{ value: 'editor-paste-text', label: 'Editor Paste Text' },
	{ value: 'editor-paste-word', label: 'Editor Paste Word' },
	{ value: 'editor-quote', label: 'Editor Quote' },
	{ value: 'editor-removeformatting', label: 'Editor Remove Formatting' },
	{ value: 'editor-rtl', label: 'Editor RTL' },
	{ value: 'editor-spellcheck', label: 'Editor Spellcheck' },
	{ value: 'editor-strikethrough', label: 'Editor Strikethrough' },
	{ value: 'editor-textcolor', label: 'Editor Text Color' },
	{ value: 'editor-ul', label: 'Editor UL' },
	{ value: 'editor-underline', label: 'Editor Underline' },
	{ value: 'editor-unlink', label: 'Editor Unlink' },
	{ value: 'editor-video', label: 'Editor Video' },	{ value: 'email', label: 'Email' },
	{ value: 'email-alt', label: 'Email Alt' },
	{ value: 'excerpt-view', label: 'Excerpt View' },
	{ value: 'external', label: 'External' },
	{ value: 'facebook', label: 'Facebook' },
	{ value: 'facebook-alt', label: 'Facebook Alt' },
	{ value: 'feedback', label: 'Feedback' },
	{ value: 'flag', label: 'Flag' },
	{ value: 'format-aside', label: 'Format Aside' },
	{ value: 'format-audio', label: 'Format Audio' },
	{ value: 'format-chat', label: 'Format Chat' },
	{ value: 'format-image', label: 'Format Image' },
	{ value: 'format-gallery', label: 'Format Gallery' },
	{ value: 'format-links', label: 'Format Links' },
	{ value: 'format-quote', label: 'Format Quote' },
	{ value: 'format-standard', label: 'Format Standard' },
	{ value: 'format-status', label: 'Format Status' },
	{ value: 'format-video', label: 'Format Video' },
	{ value: 'forms', label: 'Forms' },
	{ value: 'googleplus', label: 'Google+' },
	{ value: 'groups', label: 'Groups' },
	{ value: 'hammer', label: 'Hammer' },
	{ value: 'heart', label: 'Heart' },
	{ value: 'id', label: 'ID' },
	{ value: 'id-alt', label: 'ID Alt' },
	{ value: 'image-crop', label: 'Image Crop' },
	{ value: 'image-flip-vertical', label: 'Image Flip Vertical' },
	{ value: 'image-flip-horizontal', label: 'Image Flip Horizontal' },
	{ value: 'image-rotate-left', label: 'Image Rotate Left' },
	{ value: 'image-rotate-right', label: 'Image Rotate Right' },
	{ value: 'images-alt', label: 'Images Alt' },
	{ value: 'images-alt2', label: 'Images Alt 2' },
	{ value: 'info', label: 'Info' },
	{ value: 'leftright', label: 'LeftRight' },
	{ value: 'lightbulb', label: 'Lightbulb' },
	{ value: 'list-view', label: 'List View' },
	{ value: 'location', label: 'Location' },
	{ value: 'location-alt', label: 'Location Alt' },
	{ value: 'lock', label: 'Lock' },
	{ value: 'marker', label: 'Marker' },
	{ value: 'media-archive', label: 'Media Archive' },
	{ value: 'media-audio', label: 'Media Audio' },
	{ value: 'media-code', label: 'Media Code' },
	{ value: 'media-default', label: 'Media Default' },
	{ value: 'media-document', label: 'Media Document' },
	{ value: 'media-interactive', label: 'Media Interactive' },
	{ value: 'media-spreadsheet', label: 'Media Spreadsheet' },
	{ value: 'media-text', label: 'Media Text' },
	{ value: 'media-video', label: 'Media Video' },
	{ value: 'megaphone', label: 'Megaphone' },
	{ value: 'menu', label: 'Menu' },
	{ value: 'microphone', label: 'Microphone' },
	{ value: 'migrate', label: 'Migrate' },
	{ value: 'minus', label: 'Minus' },
	{ value: 'nametag', label: 'Nametag' },
	{ value: 'networking', label: 'Networking' },
	{ value: 'no', label: 'No' },
	{ value: 'no-alt', label: 'No Alt' },
	{ value: 'performance', label: 'Performance' },
	{ value: 'phone', label: 'Phone' },
	{ value: 'playlist-audio', label: 'Playlist Audio' },
	{ value: 'playlist-video', label: 'Playlist Video' },
	{ value: 'plus', label: 'Plus' },
	{ value: 'plus-alt', label: 'Plus Alt' },
	{ value: 'portfolio', label: 'Portfolio' },
	{ value: 'post-status', label: 'Post Status' },
	{ value: 'post-trash', label: 'Post Trash' },
	{ value: 'pressthis,', label: 'PressThis' },
	{ value: 'products', label: 'Products' },
	{ value: 'randomize', label: 'Randomize' },
	{ value: 'redo', label: 'Redo' },
	{ value: 'rss', label: 'RSS' },
	{ value: 'schedule', label: 'Schedule' },
	{ value: 'screenoptions', label: 'Screen Options' },
	{ value: 'search', label: 'Search' },
	{ value: 'share', label: 'Share' },
	{ value: 'share1', label: 'Share 1' },
	{ value: 'share-alt', label: 'Share Alt' },
	{ value: 'share-alt2', label: 'Share Alt 2' },
	{ value: 'shield', label: 'Shield' },
	{ value: 'shield-alt', label: 'Shield Alt' },
	{ value: 'slides', label: 'Slides' },
	{ value: 'smartphone', label: 'Smartphone' },
	{ value: 'smiley', label: 'Smiley' },
	{ value: 'sort', label: 'Sort' },
	{ value: 'sos', label: 'SOS' },
	{ value: 'star-empty', label: 'Star Empty' },
	{ value: 'star-filled', label: 'Star Filled' },
	{ value: 'star-half', label: 'Star Half' },
	{ value: 'tablet', label: 'Tablet' },
	{ value: 'tag', label: 'Tag' },
	{ value: 'tagcloud', label: 'Tagcloud' },
	{ value: 'testimonial', label: 'Testimonial' },
	{ value: 'text', label: 'Text' },
	{ value: 'tickets', label: 'Tickets' },
	{ value: 'translation', label: 'Translation' },
	{ value: 'trash', label: 'Trash' },
	{ value: 'twitter', label: 'Twitter' },
	{ value: 'undo', label: 'Undo' },
	{ value: 'universal-access', label: 'Universal Access' },
	{ value: 'universal-access-alt', label: 'Universal Access Alt' },
	{ value: 'update,', label: 'Update' },
	{ value: 'upload', label: 'Upload' },
	{ value: 'vault', label: 'Vault' },
	{ value: 'video-alt', label: 'Video Alt' },
	{ value: 'video-alt2', label: 'Video Alt 2' },
	{ value: 'video-alt3', label: 'Video Alt 3' },
	{ value: 'visibility', label: 'Visibility' },
	{ value: 'welcome-add-page', label: 'Welcome Add Page' },
	{ value: 'welcome-comments', label: 'Welcome Comments' },
	{ value: 'welcome-edit-page', label: 'Welcome Edit Page' },
	{ value: 'welcome-learn-more', label: 'Welcome Learn More' },
	{ value: 'welcome-write-blog', label: 'Welcome Write Blog' },
	{ value: 'welcome-view-site', label: 'Welcome View Site' },
	{ value: 'welcome-widgets-menus', label: 'Welcome Widgets Menus' },
	{ value: 'wordpress', label: 'WordPress' },
	{ value: 'wordpress-alt', label: 'WordPress Alt' },
	{ value: 'yes', label: 'Yes' },
];
